# ----------------------- #
#      Main Configs       #
# ----------------------- #
baseurl: ""
url: http://euts.github.io
title: EUTS
tagline: Effat University Tech Society
email: your-email@domain.com
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."


# Team names, titles and social links
people:
- name: Yumna Aziz
  pic: 2
  position: Leader
  social:
    - title: facebook
      url: https://www.facebook.com/yumnaansari
    - title: github
      url: https://github.com/doubleoseven
    - title: linkedin
      url: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:categories/:title

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/euts
