# Site settings
title:  EUTS  
email: hamohammed.sa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Website for our little community. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://euts.github.io" # the base hostname & protocol for your site
github_username:  EUTS

# Build settings
markdown: kramdown
