- img: who.png
  category: Services
  title: Who are we?
  description: We’re a group of students who come together to brainstorm ideas, develop and share code, improve our skills and discuss anything related to programming and technology.
- img: what.png
  category: Services
  title: What do we do?
  description: Hacking, Web development, Mobile Development, Game development … You name it!
- img: join.png
  category: Services
  title: Share you knowledge! 
  description: Write about a project you're working on, a new tool you've learned, or a tutorial to help others. To learn more on how to post check out this
