- img: who.png
  category: Services
  title: Who are we?
  description: We’re a group of students who come together to brainstorm ideas, develop and share code, improve our skills and discuss anything related to programming and technology.
- img: what.png
  category: Services
  title: What do we do?
  description: Hacking, Web development, Mobile Development, Game development … You name it!
- img: join.png
  category: Services
  title: What is our goal?
  description: To provide ourselves with the opportunities to work on team projects, learn new skills, and develop our current ones in a fun, welcoming environment.

