- img: who.png
  category: Services
  title: Who are we?
  description: We’re a group of students who come together to brainstorm ideas, develop and share code, improve our skills and discuss anything related to programming and technology.
- img: what.png
  category: Services
  title: What do we do?
  description: Hacking, Web development, Mobile Development, Game development … You name it!
